pluginManagement {
    repositories {
        mavenLocal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Minecraft libraries'
            url = 'https://libraries.minecraft.net'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "voxkbd-fabric-1.21.6_1.21.8"
