org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.java.home=C:/Program Files/Java/jdk-21
org.gradle.java.installations.paths=C:/Program Files/Java/jdk-21

mod_id=voxkbd
mod_version=1.0.1-1.21.9_1.21.10-fabric
mod_group_id=com.voxkbd
mod_license=MIT

minecraft_version=1.21.9
minecraft_version_range=>=1.21.9 <=1.21.10
java_version=21
release_bytecode=21
fabric_loader_version=0.16.10
fabric_version=0.134.1+1.21.9
