plugins {
    id 'net.neoforged.moddev' version '2.0.143'
}

version = "1.0.1-1.21.11-neoforge"
group = "com.voxkbd"
base { archivesName = "voxkbd" }

repositories {
    maven {
        name = 'Minecraft libraries'
        url = 'https://libraries.minecraft.net'
    }
    mavenCentral()
}

neoForge {
    enable {
        version = project.neo_version
        disableRecompilation = true
    }

    runs {
        client { client() }
        server { server() }
    }

    mods {
        "voxkbd" {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
        mod_id                 : 'voxkbd',
        mod_version            : '1.0.1',
        mod_license            : 'MIT',
        minecraft_version      : '1.21.11',
        minecraft_version_range: '[1.21.11,1.22)',
        neo_version_range      : '[21.11,)',
        loader_version_range   : '[1,)',
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    manifest.attributes(['MixinConfigs': 'voxkbd.mixins.json'])
    from("../../LICENSE") {}
}
