modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "voxkbd"
version = "1.0.1"
displayName = "Vox Kbd"
authors = "VoxKbd"
description = '''
Virtual keyboards: an infinitely extensible key layer for modpacks without touching vanilla bindings.
'''

[[dependencies.voxkbd]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.voxkbd]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "CLIENT"
