pluginManagement {
    repositories {
        mavenLocal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'SpongePowered'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "voxkbd-forge-1.20_1.20.1"
